version: "3.7"

services:
  database_ftt:
    image: postgres
    container_name: database_ftt
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ftt123
      - POSTGRES_DB=ftt
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: ftt_backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_ftt
    depends_on: 
      - database_ftt

volumes:
  pgdata:
    driver: local